import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Link, useParams } from 'react-router-dom'
import type { Vessel } from '../lib/purchasing'
import { createIceWorkRecord, parseIceBoxHalfUnits, parseKgToGrams, parseLitersToMilliliters, type IceWorkRecord } from '../lib/iceWork'
import { malaysiaBusinessDate, monthKeyFromBusinessDate } from '../lib/businessDate'
import { loadVessels } from '../services/purchaseMasterData'
import { confirmIceWorkRecordInStore, loadIceWorkRecords, saveIceWorkRecord, voidIceWorkRecord } from '../services/iceWork'

const makeId=()=>`ice_${globalThis.crypto?.randomUUID?.().replaceAll('-','')??Date.now().toString(36)}`
const money=(cents:number)=>`RM ${(cents/100).toFixed(2)}`
type Values={factory:string;boxes:string;diesel:string;hawker:string;directIce:string;bags:string}
const empty:Values={factory:'',boxes:'',diesel:'',hawker:'',directIce:'',bags:''}
interface Props { vesselLoader?:()=>Promise<Vessel[]>; recordLoader?:(vesselId:string,monthKey:string)=>Promise<IceWorkRecord[]>; saver?:(record:IceWorkRecord)=>Promise<IceWorkRecord>; confirmer?:(record:IceWorkRecord)=>Promise<IceWorkRecord>; voider?:(record:IceWorkRecord,reason:string)=>Promise<IceWorkRecord>; today?:()=>string }

export function IceVesselPage({vesselLoader=loadVessels,recordLoader=loadIceWorkRecords,saver=saveIceWorkRecord,confirmer=confirmIceWorkRecordInStore,voider=voidIceWorkRecord,today=malaysiaBusinessDate}:Props){
  const {vesselId=''}=useParams();const [vessels,setVessels]=useState<Vessel[]>([]);const [records,setRecords]=useState<IceWorkRecord[]>([]);const [workDate,setWorkDate]=useState(today());const [values,setValues]=useState<Values>(empty);const [notes,setNotes]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const vessel=useMemo(()=>vessels.find(item=>item.id===vesselId||item.vesselCode===vesselId),[vessels,vesselId]);const monthKey=useMemo(()=>{try{return monthKeyFromBusinessDate(workDate)}catch{return ''}},[workDate])
  useEffect(()=>{void vesselLoader().then(setVessels).catch(()=>setError('无法载入船号。'))},[vesselLoader]);useEffect(()=>{if(vessel&&monthKey)void recordLoader(vessel.id,monthKey).then(setRecords).catch(()=>setError('无法载入冰工记录。'))},[vessel,monthKey,recordLoader])
  const preview=useMemo(()=>{if(!vessel||!monthKey)return null;try{return createIceWorkRecord({id:'preview',workDate,vesselId:vessel.id,vesselCodeSnapshot:vessel.vesselCode,vesselNameSnapshot:vessel.displayName,createdBy:'',factoryIncomingWeightGrams:parseKgToGrams(values.factory),iceBoxHalfUnits:parseIceBoxHalfUnits(values.boxes),dieselVolumeMilliliters:parseLitersToMilliliters(values.diesel),hawkerSaleWeightGrams:parseKgToGrams(values.hawker),directIceBarCount:values.directIce.trim()?Number(values.directIce):0,plasticBagCount:values.bags.trim()?Number(values.bags):0,notes})}catch{return null}},[vessel,monthKey,workDate,values,notes])
  const set=(key:keyof Values,value:string)=>setValues(current=>({...current,[key]:value}))
  async function submit(event:FormEvent,confirm:boolean){event.preventDefault();if(!vessel||!preview)return;setBusy(true);setError('');try{const saved=await saver({...preview,id:makeId()});const final=confirm?await confirmer(saved):saved;setRecords(current=>[final,...current]);setValues(empty);setNotes('');window.dispatchEvent(new Event('ccm:form-saved'))}catch(problem){setError(problem instanceof Error?problem.message:'无法保存冰工记录。')}finally{setBusy(false)}}
  async function voidRecord(record:IceWorkRecord){const reason=window.prompt('请输入作废原因')?.trim();if(!reason)return;try{const updated=await voider(record,reason);setRecords(current=>current.map(item=>item.id===updated.id?updated:item))}catch(problem){setError(problem instanceof Error?problem.message:'无法作废记录。')}}
  return <main><header><p className="eyebrow">CCM Fishery</p><h1>冰工船 {vessel?.vesselCode??vesselId}</h1><Link className="page-link" to="/ice-department">← 返回冰工部门</Link></header>{!vessel?<p className="notice">未找到该船号。</p>:<><form className="master-form ice-work-form" onSubmit={event=>void submit(event,false)}><h2>新增冰工记录</h2><label>日期（DD/MM/YYYY）<input aria-label="日期" placeholder="DD/MM/YYYY" value={workDate} onChange={event=>setWorkDate(event.target.value)}/></label>
    <IceInput label="木斑什进厂重量（kg）" value={values.factory} update={value=>set('factory',value)} rate="RM 0.10/kg" amount={preview?.factoryIncomingAmountCents}/><IceInput label="冰箱子数量（箱）" value={values.boxes} update={value=>set('boxes',value)} rate="RM 30.00/箱；可输入半箱" amount={preview?.iceBoxAmountCents}/><IceInput label="柴油数量（公升）" value={values.diesel} update={value=>set('diesel',value)} rate="RM 0.02/L" amount={preview?.dieselAmountCents}/><IceInput label="卖给小贩重量（kg）" value={values.hawker} update={value=>set('hawker',value)} rate="RM 0.30/kg" amount={preview?.hawkerSaleAmountCents}/><IceInput label="直接买冰（条）" value={values.directIce} update={value=>set('directIce',value)} rate="RM 13.50/条" amount={preview?.directIceAmountCents}/><IceInput label="塑料袋（个）" value={values.bags} update={value=>set('bags',value)} rate="RM 1.40/个" amount={preview?.plasticBagAmountCents}/><label>备注<textarea value={notes} onChange={event=>setNotes(event.target.value)}/></label>{preview&&<section className="notice"><p>冰工工钱小计：{money(preview.workFeeSubtotalCents)}</p><p>材料费小计：{money(preview.materialSubtotalCents)}</p><strong>本次合计：{money(preview.recordTotalCents)}</strong></section>}{error&&<p className="error" role="alert">{error}</p>}<div className="master-actions"><button className="primary-action" disabled={busy||!preview}>保存草稿</button><button type="button" className="activate-action" disabled={busy||!preview} onClick={event=>void submit(event as unknown as FormEvent,true)}>确认记录</button></div></form>
    <section className="master-card-list"><h2>{monthKey} 记录</h2><Link className="page-link" to={`/ice-department/${vessel.id}/monthly?month=${encodeURIComponent(monthKey)}`}>月度结算</Link>{records.map(record=><article className="master-card" key={record.id}><strong>{record.workDate}</strong><span>{record.status==='confirmed'?'已确认':record.status==='voided'?'已作废':'草稿'}</span><p>工钱 {money(record.workFeeSubtotalCents)} · 材料 {money(record.materialSubtotalCents)} · 合计 {money(record.recordTotalCents)}</p>{record.status!=='voided'&&<button type="button" className="danger-action" onClick={()=>void voidRecord(record)}>作废</button>}</article>)}</section></>}</main>
}
function IceInput({label,value,update,rate,amount}:{label:string;value:string;update:(value:string)=>void;rate:string;amount?:number}){return <label>{label}<small>{rate} {amount===undefined?'':`· ${money(amount)}`}</small><input aria-label={label} inputMode="decimal" value={value} onChange={event=>update(event.target.value)}/></label>}
