import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { RetailFishPage, RetailHistoryPage, RetailReceiptPage, RetailSalesPage } from './RetailSalesPage'
import { prepareRetailSale, type RetailFish, type RetailSale } from '../lib/retailSales'
import { legacyIsoDateFromBusinessDate } from '../lib/businessDate'
import { retailToday } from '../lib/retailSales'
import type { RetailHistoryRange } from '../lib/retailHistory'

const services = vi.hoisted(() => ({ watch: vi.fn(), save: vi.fn(), saveFish: vi.fn(), quickAdd: vi.fn(), initialize: vi.fn(), history: vi.fn(), detail: vi.fn(), id: vi.fn(), restore: vi.fn(), remember: vi.fn(), clear: vi.fn() }))
vi.mock('../lib/retailInvoicePdf', () => ({ createRetailInvoicePdf: vi.fn(async () => new File(['%PDF-1.4'], 'receipt.pdf', { type: 'application/pdf' })) }))
vi.mock('../services/retailSales', () => ({ watchRetailFish: services.watch, saveRetailSale: services.save, saveRetailFish: services.saveFish, quickAddRetailFish: services.quickAdd, initializeRetailFish: services.initialize, loadRetailSales: services.history, loadRetailSale: services.detail, newRetailSaleId: services.id, loadPendingRetailSale: services.restore, rememberPendingRetailSale: services.remember, clearPendingRetailSale: services.clear,
  watchRetailSales: (range: RetailHistoryRange, next: (snapshot: { sales: RetailSale[]; fromCache: boolean }) => void, error: (problem: unknown) => void) => {
    let current = true
    void services.history(range).then((sales: RetailSale[]) => { if (current) next({ sales, fromCache: false }) }).catch(error)
    return () => { current = false }
  },
}))
const fish: RetailFish[] = [
  { id: 'a', chineseName: '甘丰', malayName: 'kembung', suggestedPriceCents: 600, active: true },
  { id: 'b', chineseName: '马丰', malayName: 'mabong', suggestedPriceCents: 800, active: true },
  { id: 'c', chineseName: '无建议鱼', malayName: '', suggestedPriceCents: null, active: true },
  { id: 'd', chineseName: '停用 Inactive鱼', malayName: '', suggestedPriceCents: 100, active: false },
]
function mount(page = <RetailSalesPage />) { return render(<MemoryRouter>{page}</MemoryRouter>) }
function fill(label: string, value: string) { fireEvent.change(screen.getByLabelText(label), { target: { value } }) }
function add(name = '甘丰', kg = '2', price?: string) {
  fill('鱼名 Fish', name)
  fireEvent.click(screen.getByRole('option', { name: new RegExp(name) }))
  fill('重量 Weight (kg)', kg)
  if (price !== undefined) fill('单价 Unit Price (RM/kg)', price)
  fireEvent.click(screen.getByRole('button', { name: '加入明细 Add Item' }))
}
beforeEach(() => {
  vi.clearAllMocks()
  services.watch.mockImplementation(next => { next(fish); return vi.fn() })
  services.id.mockReturnValue('sale-1')
  services.save.mockImplementation(async (id, input) => ({ id, ...prepareRetailSale(input) }))
  services.saveFish.mockResolvedValue(undefined)
  services.quickAdd.mockImplementation(async input => ({ id: 'new-fish', ...input }))
  services.restore.mockReturnValue(null)
})
afterEach(cleanup)

describe('mobile retail checkout', () => {
  it('shows Chinese, Malay and suggested price while typing and selects by keyboard without adding a line', () => {
    mount()
    const input = screen.getByRole('combobox', { name: '鱼名 Fish' })
    expect(input).toHaveFocus()
    fill('鱼名 Fish', '甘')
    expect(screen.getByRole('option', { name: '甘丰 kembung RM6.00/kg' })).toBeInTheDocument()
    expect(screen.queryByRole('option', { name: /马丰/ })).not.toBeInTheDocument()
    fireEvent.compositionStart(input)
    fireEvent.keyDown(input, { key: 'Enter', isComposing: true })
    expect(screen.getByLabelText('单价 Unit Price (RM/kg)')).toHaveValue('')
    fireEvent.compositionEnd(input)
    fireEvent.keyDown(input, { key: 'ArrowDown' }); fireEvent.keyDown(input, { key: 'Enter' })
    expect(screen.getByLabelText('单价 Unit Price (RM/kg)')).toHaveValue('6.00')
    expect(screen.getByLabelText('重量 Weight (kg)')).toHaveFocus()
    expect(screen.getByRole('heading', { name: '本单明细 Items (0)' })).toBeInTheDocument()
    fill('鱼名 Fish', 'MABONG')
    expect(screen.getByRole('option', { name: '马丰 mabong RM8.00/kg' })).toBeInTheDocument()
    expect(screen.getByLabelText('单价 Unit Price (RM/kg)')).toHaveValue('')
    expect(screen.getByRole('button', { name: '加入明细 Add Item' })).toBeDisabled()
  })
  it('creates inline, preserves the sale, and uses the saved fish before its subscription update', async () => {
    let resolveCreate: (item: RetailFish) => void = () => {}
    services.quickAdd.mockReturnValue(new Promise<RetailFish>(resolve => { resolveCreate = resolve }))
    mount(); fill('日期 Date', '2026-09-05'); fill('小贩 Vendor', '阿明'); add()
    expect(screen.getByRole('combobox', { name: '鱼名 Fish' })).toHaveFocus()
    fill('鱼名 Fish', '红鱼'); fireEvent.click(screen.getByRole('button', { name: '新增 Add「红鱼」' }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(screen.getByLabelText('新鱼马来文名 New Fish Malay Name')).toHaveFocus()
    fill('新鱼马来文名 New Fish Malay Name', 'merah'); fill('新鱼建议单价 New Fish Suggested Price (RM/kg)', '12')
    fireEvent.click(screen.getByRole('button', { name: '保存并使用新鱼 Save and Use Fish' }))
    fireEvent.click(screen.getByRole('button', { name: '正在新增… Adding fish…' }))
    expect(services.quickAdd).toHaveBeenCalledOnce()
    expect(screen.getByRole('button', { name: '结算 Checkout' })).toBeDisabled()
    await act(async () => resolveCreate({ id: 'red', chineseName: '红鱼', malayName: 'merah', suggestedPriceCents: 1200, active: true }))
    expect(screen.getByLabelText('重量 Weight (kg)')).toHaveFocus()
    expect(screen.getByLabelText('单价 Unit Price (RM/kg)')).toHaveValue('12.00')
    expect(screen.getByLabelText('日期 Date')).toHaveValue('2026-09-05')
    expect(screen.getByLabelText('小贩 Vendor')).toHaveValue('阿明')
    expect(screen.getByRole('heading', { name: '本单明细 Items (1)' })).toBeInTheDocument()
    fill('重量 Weight (kg)', '12.5'); fill('单价 Unit Price (RM/kg)', '11.50')
    fireEvent.click(screen.getByRole('button', { name: '加入明细 Add Item' }))
    expect(screen.getByRole('combobox', { name: '鱼名 Fish' })).toHaveFocus()
    fill('鱼名 Fish', 'merah')
    expect(screen.getByRole('option', { name: '红鱼 merah RM12.00/kg' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '清除当前品名 Clear Fish' }))
    fireEvent.click(screen.getByRole('button', { name: '结算 Checkout' }))
    const receipt = await screen.findByRole('region', { name: '门市现金结算单' })
    expect(within(receipt).getByText('红鱼')).toBeInTheDocument()
    expect(within(receipt).getByText('merah')).toBeInTheDocument()
    expect(within(receipt).getByRole('cell', { name: '11.50' })).toBeInTheDocument()
    expect(services.save.mock.calls[0][1].lines[1]).toMatchObject({ fishId: 'red', chineseName: '红鱼', malayName: 'merah', weightDeciKg: 125, unitPriceCents: 1150, amountCents: 14375 })
  })
  it('keeps keyboard selection valid when a live master update removes highlighted suggestions', () => {
    let next: (items: RetailFish[]) => void = () => {}
    services.watch.mockImplementation(callback => { next = callback; callback(fish); return vi.fn() })
    mount()
    const input = screen.getByRole('combobox', { name: '鱼名 Fish' })
    fireEvent.keyDown(input, { key: 'ArrowDown' }); fireEvent.keyDown(input, { key: 'ArrowDown' }); fireEvent.keyDown(input, { key: 'ArrowDown' })
    act(() => next([fish[0]]))
    fireEvent.keyDown(input, { key: 'Enter' })
    expect(screen.getByLabelText('单价 Unit Price (RM/kg)')).toHaveValue('6.00')
    expect(screen.getByLabelText('重量 Weight (kg)')).toHaveFocus()
  })
  it('starts from an empty master and requires Malay and suggested price before using a new fish', async () => {
    services.watch.mockImplementation(next => { next([]); return vi.fn() })
    mount(); fill('鱼名 Fish', '红鱼'); fireEvent.click(screen.getByRole('button', { name: '新增 Add「红鱼」' }))
    expect(screen.getByLabelText('新鱼马来文名 New Fish Malay Name')).toBeRequired()
    expect(screen.getByLabelText('新鱼建议单价 New Fish Suggested Price (RM/kg)')).toBeRequired()
    expect(screen.getByRole('button', { name: '加入明细 Add Item' })).toBeDisabled()
    fill('新鱼马来文名 New Fish Malay Name', '   '); fill('新鱼建议单价 New Fish Suggested Price (RM/kg)', '12')
    fireEvent.click(screen.getByRole('button', { name: '保存并使用新鱼 Save and Use Fish' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('马来文名')
    fill('新鱼马来文名 New Fish Malay Name', 'merah'); fill('新鱼建议单价 New Fish Suggested Price (RM/kg)', '0')
    fireEvent.click(screen.getByRole('button', { name: '保存并使用新鱼 Save and Use Fish' }))
    expect(screen.getByRole('alert')).toHaveTextContent('售价')
    expect(services.quickAdd).not.toHaveBeenCalled()
    fill('新鱼建议单价 New Fish Suggested Price (RM/kg)', '12'); fireEvent.click(screen.getByRole('button', { name: '保存并使用新鱼 Save and Use Fish' }))
    await waitFor(() => expect(screen.getByLabelText('单价 Unit Price (RM/kg)')).toHaveValue('12.00'))
    fill('重量 Weight (kg)', '7.3'); fireEvent.click(screen.getByRole('button', { name: '加入明细 Add Item' }))
    expect(screen.getByText('7.3 kg × RM12.00/kg')).toBeInTheDocument()
  })
  it('preserves failed quick-add values and existing lines, and clears or cancels without creating a sale', async () => {
    services.quickAdd.mockRejectedValueOnce(new Error('网络中断，请重试'))
    mount(); fill('小贩 Vendor', '阿明'); add(); fill('鱼名 Fish', '红鱼')
    fireEvent.click(screen.getByRole('button', { name: '结算 Checkout' }))
    expect(screen.getByRole('alert')).toHaveTextContent('请先加入或清除')
    fireEvent.click(screen.getByRole('button', { name: '新增 Add「红鱼」' }))
    fill('新鱼马来文名 New Fish Malay Name', 'merah'); fill('新鱼建议单价 New Fish Suggested Price (RM/kg)', '12')
    fireEvent.click(screen.getByRole('button', { name: '保存并使用新鱼 Save and Use Fish' }))
    await screen.findByText('网络中断，请重试')
    expect(screen.getByLabelText('新鱼马来文名 New Fish Malay Name')).toHaveValue('merah')
    expect(screen.getByLabelText('新鱼建议单价 New Fish Suggested Price (RM/kg)')).toHaveValue('12')
    expect(screen.getByRole('heading', { name: '本单明细 Items (1)' })).toBeInTheDocument()
    expect(screen.getByLabelText('小贩 Vendor')).toHaveValue('阿明')
    expect(screen.getByRole('button', { name: '加入明细 Add Item' })).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: '取消新增 Cancel Add' }))
    expect(screen.getByRole('combobox', { name: '鱼名 Fish' })).toHaveFocus()
    fireEvent.click(screen.getByRole('button', { name: '新增 Add「红鱼」' }))
    fireEvent.click(screen.getByRole('button', { name: '清除当前品名 Clear Fish' }))
    expect(screen.queryByLabelText('新增门市鱼种 Add Retail Fish')).not.toBeInTheDocument()
    expect(screen.getByRole('combobox', { name: '鱼名 Fish' })).toHaveValue('')
    expect(screen.getByRole('combobox', { name: '鱼名 Fish' })).toHaveFocus()
    expect(services.save).not.toHaveBeenCalled()
  })
  it('accepts decimal kg, shows exact draft amounts, and preserves weights on the saved printable receipt', async () => {
    mount(); fill('小贩 Vendor', '阿明')
    expect(screen.getByLabelText('重量 Weight (kg)')).toHaveAttribute('inputmode', 'decimal')
    fireEvent.click(screen.getByRole('option', { name: /甘丰/ })); fill('重量 Weight (kg)', '12.5')
    expect(screen.getByText('RM75.00')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '加入明细 Add Item' }))
    add('马丰', '7.3')
    expect(screen.getByText('12.5 kg × RM6.00/kg')).toBeInTheDocument()
    expect(screen.getByText('7.3 kg × RM8.00/kg')).toBeInTheDocument()
    expect(screen.getByText('RM133.40')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '结算 Checkout' }))
    const receipt = await screen.findByRole('region', { name: '门市现金结算单' })
    expect(within(receipt).getByRole('cell', { name: '12.5' })).toBeInTheDocument()
    expect(within(receipt).getByRole('cell', { name: '7.3' })).toBeInTheDocument()
    expect(within(receipt).getByRole('cell', { name: '75.00' })).toBeInTheDocument()
    expect(within(receipt).getByRole('cell', { name: '58.40' })).toBeInTheDocument()
    expect(services.save.mock.calls[0][1]).toMatchObject({ lines: [{ weightDeciKg: 125, amountCents: 7500 }, { weightDeciKg: 73, amountCents: 5840 }] })
  })
  it('rejects two decimal places explicitly without adding or rounding the weight', () => {
    mount(); add('甘丰', '2.25')
    expect(screen.getByRole('alert')).toHaveTextContent('最多一位小数')
    expect(screen.getByLabelText('重量 Weight (kg)')).toHaveValue('2.25')
    expect(screen.getByRole('button', { name: '结算 Checkout' })).toBeDisabled()
    expect(services.save).not.toHaveBeenCalled()
  })
  it('retains vendor/date across lines, accepts overrides, saves once, prints, and starts next vendor', async () => {
    const print = vi.spyOn(window, 'print').mockImplementation(() => {})
    mount()
    expect(screen.getByLabelText('日期 Date')).toHaveValue(legacyIsoDateFromBusinessDate(retailToday()))
    fill('日期 Date', '2026-09-05'); fill('小贩 Vendor', '阿明')
    fireEvent.click(screen.getByRole('option', { name: /甘丰/ }))
    expect(screen.getByLabelText('单价 Unit Price (RM/kg)')).toHaveValue('6.00')
    fill('重量 Weight (kg)', '3'); fill('单价 Unit Price (RM/kg)', '6.15')
    fireEvent.click(screen.getByRole('button', { name: '加入明细 Add Item' }))
    expect(screen.getByLabelText('重量 Weight (kg)')).toHaveValue('')
    expect(screen.getByLabelText('小贩 Vendor')).toHaveValue('阿明')
    expect(screen.getByLabelText('日期 Date')).toHaveValue('2026-09-05')
    add('马丰', '2')
    expect(screen.getByText('RM34.45')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '结算 Checkout' }))
    fireEvent.click(screen.getByRole('button', { name: '正在保存… Saving…' }))
    expect(await screen.findByText('现金结算已保存。 Cash sale saved.')).toBeInTheDocument()
    expect(services.save).toHaveBeenCalledOnce()
    expect(services.save.mock.calls[0][1]).toMatchObject({ vendorName: '阿明', businessDate: '05/09/2026', lines: [{ unitPriceCents: 615 }, { unitPriceCents: 800 }] })
    expect(screen.getByRole('button', { name: 'PDF / 分享 PDF / Share' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '打印 Print' })); expect(print).toHaveBeenCalledOnce()
    fireEvent.click(screen.getByRole('button', { name: '下一位小贩 Next Vendor' }))
    expect(screen.getByLabelText('小贩 Vendor')).toHaveValue('')
    expect(screen.getByText('RM0.00')).toBeInTheDocument()
    print.mockRestore()
  })
  it('searches names, hides inactive species, accepts a missing default, and removes draft lines', () => {
    mount(); expect(screen.queryByRole('option', { name: /停用 Inactive鱼/ })).not.toBeInTheDocument()
    fill('鱼名 Fish', 'mabong'); expect(screen.queryByRole('option', { name: /甘丰/ })).not.toBeInTheDocument()
    fill('鱼名 Fish', ''); add('无建议鱼', '5', '1.01')
    expect(screen.getAllByText('RM5.05')).toHaveLength(2)
    fireEvent.click(screen.getByRole('button', { name: '移除第 1 条明细 Remove Item 1' }))
    expect(screen.getByRole('button', { name: '结算 Checkout' })).toBeDisabled()
  })
  it('uses Master names and default price but keeps this invoice price override out of Master Data', async () => {
    const original = JSON.stringify(fish)
    mount(); fill('小贩 Vendor', '阿明')
    fireEvent.click(screen.getByRole('option', { name: /甘丰/ }))
    expect(screen.getByRole('combobox')).toHaveValue('甘丰')
    expect(screen.getByLabelText('单价 Unit Price (RM/kg)')).toHaveValue('6.00')
    expect(screen.getByText(/甘丰 · kembung · 建议 Suggested/)).toBeInTheDocument()
    fill('重量 Weight (kg)', '2'); fill('单价 Unit Price (RM/kg)', '5.25')
    fireEvent.click(screen.getByRole('button', { name: '加入明细 Add Item' }))
    fireEvent.click(screen.getByRole('button', { name: '结算 Checkout' }))
    await screen.findByText('现金结算已保存。 Cash sale saved.')
    expect(services.save.mock.calls[0][1].lines[0]).toMatchObject({ chineseName: '甘丰', malayName: 'kembung', unitPriceCents: 525, amountCents: 1050 })
    expect(services.saveFish).not.toHaveBeenCalled()
    expect(services.quickAdd).not.toHaveBeenCalled()
    expect(JSON.stringify(fish)).toBe(original)
  })
  it('opens Other without leaving the previous fish available to add accidentally', async () => {
    mount(); fill('小贩 Vendor', '阿明'); add()
    fireEvent.click(screen.getByRole('option', { name: /马丰/ }))
    fill('重量 Weight (kg)', '3')
    fireEvent.click(screen.getByRole('button', { name: '其他 Other' }))
    expect(screen.getByLabelText('重量 Weight (kg)')).toHaveValue('')
    expect(screen.getByLabelText('单价 Unit Price (RM/kg)')).toHaveValue('')
    expect(screen.getByRole('button', { name: '加入明细 Add Item' })).toBeDisabled()
    expect(screen.getByRole('heading', { name: '本单明细 Items (1)' })).toBeInTheDocument()
    fill('新鱼中文正式名 New Fish Chinese Name', '红鱼')
    fill('新鱼马来文名 New Fish Malay Name', 'Merah')
    fill('新鱼建议单价 New Fish Suggested Price (RM/kg)', '12.05')
    fireEvent.click(screen.getByRole('button', { name: '保存并使用新鱼 Save and Use Fish' }))
    await waitFor(() => expect(screen.getByLabelText('单价 Unit Price (RM/kg)')).toHaveValue('12.05'))
    expect(screen.getByRole('combobox')).toHaveValue('红鱼')
    expect(screen.getByLabelText('小贩 Vendor')).toHaveValue('阿明')
    expect(services.save).not.toHaveBeenCalled()
  })
  it('keeps added snapshots through live changes and makes newly added fish available immediately', () => {
    let next: (items: RetailFish[]) => void = () => {}
    services.watch.mockImplementation(callback => { next = callback; callback(fish); return vi.fn() })
    mount(); add()
    act(() => next([{ ...fish[0], chineseName: '新名称', suggestedPriceCents: 900 }, { ...fish[1], id: 'new', chineseName: '新鱼' }]))
    expect(screen.getByText('甘丰')).toBeInTheDocument()
    expect(screen.getByRole('option', { name: /新鱼/ })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('option', { name: /新名称/ }))
    expect(screen.getByLabelText('单价 Unit Price (RM/kg)')).toHaveValue('9.00')
  })
  it('retries an uncertain save using the same ID and frozen snapshot', async () => {
    services.save.mockRejectedValueOnce(new Error('连接中断'))
    mount(); fill('小贩 Vendor', '阿明'); add()
    fireEvent.click(screen.getByRole('button', { name: '结算 Checkout' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('连接中断')
    expect(screen.getByLabelText('小贩 Vendor')).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: '重试结算 Retry Checkout' }))
    await screen.findByText('现金结算已保存。 Cash sale saved.')
    expect(services.id).toHaveBeenCalledOnce()
    expect(services.save.mock.calls[1]).toEqual(services.save.mock.calls[0])
  })
  it('does not silently omit the current unadded line', async () => {
    mount(); fill('小贩 Vendor', '阿明'); add()
    fill('鱼名 Fish', '马'); fireEvent.click(screen.getByRole('option', { name: /马丰/ })); fill('重量 Weight (kg)', '3')
    fireEvent.click(screen.getByRole('button', { name: '结算 Checkout' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('请先加入或清除')
    expect(services.save).not.toHaveBeenCalled()
  })
  it('restores an interrupted checkout after a page reload', async () => {
    const pending = { id: 'old-attempt', input: prepareRetailSale({ businessDate: '05/09/2026', vendorName: '阿明', lines: [{ fishId: 'a', chineseName: '甘丰', malayName: 'kembung', weightKg: 2, unitPriceCents: 600, amountCents: 1200 }] }) }
    services.restore.mockReturnValue(pending)
    mount(); expect(screen.getByLabelText('小贩 Vendor')).toHaveValue('阿明')
    expect(screen.getByLabelText('小贩 Vendor')).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: '重试结算 Retry Checkout' }))
    await screen.findByText('现金结算已保存。 Cash sale saved.')
    expect(services.save).toHaveBeenCalledWith(pending.id, pending.input)
    expect(services.id).not.toHaveBeenCalled(); expect(services.clear).toHaveBeenCalledOnce()
  })
})

describe('retail settings and history', () => {
  it('creates a fish without Malay name or price and edits name, price, and enabled state', async () => {
    mount(<RetailFishPage />); fireEvent.click(screen.getByRole('button', { name: '新增鱼种 Add Fish' }))
    fill('中文鱼名 Chinese Fish Name', '新增鱼'); fireEvent.click(screen.getByRole('button', { name: '保存鱼种 Save Fish' }))
    await waitFor(() => expect(services.saveFish).toHaveBeenCalledWith(null, { chineseName: '新增鱼', malayName: '', suggestedPriceCents: null, active: true }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    fireEvent.click(screen.getByRole('button', { name: '修改 Edit 甘丰' }))
    fill('中文鱼名 Chinese Fish Name', '新名字'); fill('马来文名（可空） Malay Name (Optional)', 'new'); fill('建议单价（可空） Suggested Price (RM/kg, Optional)', '7.25')
    fireEvent.click(screen.getByLabelText('启用 Active')); fireEvent.click(screen.getByRole('button', { name: '保存鱼种 Save Fish' }))
    await waitFor(() => expect(services.saveFish).toHaveBeenLastCalledWith('a', { chineseName: '新名字', malayName: 'new', suggestedPriceCents: 725, active: false }))
  })
  it('initializes seed data only on explicit setup action', async () => {
    services.watch.mockImplementation(next => { next([]); return vi.fn() })
    mount(<RetailFishPage />); expect(services.initialize).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: '建立初始三种鱼 Create Three Starter Fish' }))
    await waitFor(() => expect(services.initialize).toHaveBeenCalledOnce())
  })
  it('loads date history, filters by vendor, opens stored snapshots and reprints', async () => {
    const sale: RetailSale = { id: 'old', businessDate: '06/09/2026', dateSortKey: 20260906, vendorName: '阿明', totalAmountCents: 5840, lines: [{ fishId: 'a', chineseName: '历史甘丰', malayName: 'old name', weightDeciKg: 73, unitPriceCents: 800, amountCents: 5840 }] }
    services.history.mockResolvedValue([sale, { ...sale, id: 'other', vendorName: '阿华' }]); services.detail.mockResolvedValue(sale)
    const print = vi.spyOn(window, 'print').mockImplementation(() => {})
    render(<MemoryRouter initialEntries={['/retail-sales/history']}><Routes><Route path="/retail-sales/history" element={<RetailHistoryPage />} /><Route path="/retail-sales/history/:saleId" element={<RetailReceiptPage />} /></Routes></MemoryRouter>)
    await screen.findByRole('link', { name: /查看结算单 View Invoice.*阿华/ })
    fireEvent.click(screen.getByRole('button', { name: '范围 Range' }))
    fill('开始 From', '2026-09-06'); fill('结束 To', '2026-09-06')
    await waitFor(() => expect(services.history).toHaveBeenCalledWith({ fromDate: '06/09/2026', toDate: '06/09/2026' }))
    fill('搜索小贩 Search Vendor', '阿明'); expect(screen.queryByRole('link', { name: /查看结算单 View Invoice.*阿华/ })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('link', { name: '查看结算单 View Invoice 06092026 星期日 Sun 阿明 RM58.40' }))
    const receipt = await screen.findByRole('region', { name: '门市现金结算单' })
    expect(within(receipt).getByText('历史甘丰')).toBeInTheDocument(); expect(within(receipt).getByText('old name')).toBeInTheDocument()
    expect(within(receipt).getByRole('cell', { name: '7.3' })).toBeInTheDocument()
    expect(within(receipt).getByRole('cell', { name: '58.40' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '打印 Print' })); expect(print).toHaveBeenCalledOnce(); print.mockRestore()
  })
})
